# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#D85EFF", bold = true}

# Hovered
hovered         = { fg = "#303446", bg = "#D85EFF", bold = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e5c890", italic = true }
find_position = { fg = "#f4b8e4", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#e5c890", bg = "#e5c890" }
marker_copied   = { fg = "#a6d189", bg = "#a6d189" }
marker_cut      = { fg = "#e78284", bg = "#e78284" }

# Tab
tab_active   = { fg = "#303446", bg = "#D85EFF", bold = true }
tab_inactive = { fg = "#c6d0f5", bg = "#51576d" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#838ba7" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
# separator_open  = ""
# separator_close = ""
separator_open  = ""
separator_close = ""
separator_style = { fg = "#51576d", bg = "#51576d" }
normal = { fg = "#ffd604" }
position = { fg = "#ffd604" }

# Mode
mode_normal = { fg = "#303446", bg = "#D85EFF", bold = true }
mode_select = { fg = "#303446", bg = "#a6d189", bold = true }
mode_unset  = { fg = "#303446", bg = "#eebebe", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#D85EFF", bg = "#51576d" }
progress_error  = { fg = "#e78284", bg = "#51576d" }

# Permissions
permissions_t = { fg = "#D85EFF" }
permissions_r = { fg = "#e5c890" }
permissions_w = { fg = "#e78284" }
permissions_x = { fg = "#a6d189" }
permissions_s = { fg = "#838ba7" }



# : }}}


# : Input {{{

[input]
border   = { fg = "#D85EFF" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#D85EFF" }
active   = { fg = "#f4b8e4" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#D85EFF" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#414559" }
cand            = { fg = "#D85EFF" }
rest            = { fg = "#949cbb" }
desc            = { fg = "#f4b8e4" }
separator       = ": "
# separator       = "  "
separator_style = { fg = "#626880" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#f4b8e4" }
exec    = { fg = "#D85EFF" }
desc    = { fg = "#949cbb" }
hovered = { bg = "#626880", bold = true }
footer  = { fg = "#51576d", bg = "#c6d0f5" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	# { mime = "image/*", fg = "#D85EFF",  },

	# Videos
	{ mime = "video/*", fg = "#e5c890" },
	{ mime = "audio/*", fg = "#e5c890" },

	# Archives
	{ mime = "application/zip",             fg = "#f4b8e4" },
	{ mime = "application/gzip",            fg = "#f4b8e4" },
	{ mime = "application/x-tar",           fg = "#f4b8e4" },
	{ mime = "application/x-bzip",          fg = "#f4b8e4" },
	{ mime = "application/x-bzip2",         fg = "#f4b8e4" },
	{ mime = "application/x-7z-compressed", fg = "#f4b8e4" },
	{ mime = "application/x-rar",           fg = "#f4b8e4" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#D85EFF", bold = true }
]

[icons]

"Desktop/"     = ""
"Documents/"   = ""
"Downloads/"   = ""
"Pictures/"    = ""
"Music/"       = ""
"Movies/"      = ""
"Videos/"      = ""
"Public/"      = ""
"Library/"     = ""
"Development/" = ""
".config/"     = ""


# Git
".git/"          = ""
".gitignore"     = ""
".gitmodules"    = ""
".gitattributes" = ""

# Dotfiles
".DS_Store"    = ""
".bashrc"      = ""
".bashprofile" = ""
".zshrc"       = ""
".zshenv"      = ""
".zprofile"    = ""
".vimrc"       = ""

# Text
"*.txt" = ""
"*.md"  = ""

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz"  = ""
"*.7z"  = ""

# Audio
"*.mp3"  = ""
"*.flac" = ""
"*.wav"  = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""

# Images
"*.jpg"  = ""
"*.jpeg" = ""
"*.png"  = ""
"*.gif"  = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp"  = ""
"*.ico"  = ""
"*.svg"  = ""

# Programming
"*.c"     = ""
"*.cpp"   = ""
"*.h"     = ""
"*.hpp"   = ""
"*.rs"    = ""
"*.go"    = ""
"*.py"    = ""
"*.js"    = ""
"*.ts"    = ""
"*.tsx"   = ""
"*.jsx"   = ""
"*.rb"    = ""
"*.php"   = ""
"*.java"  = ""
"*.sh"    = ""
"*.fish"  = ""
"*.swift" = ""
"*.vim"   = ""
"*.lua"   = ""
"*.html"  = ""
"*.css"   = ""
"*.scss"  = ""
"*.json"  = ""
"*.toml"  = ""
"*.yml"   = ""
"*.yaml"  = ""
"*.ini"   = ""
"*.conf"  = ""

# Default
"*"  = ""
"*/" = ""


# : }}}





