name: Feature Request
description: Suggest an idea for this project
labels: [feature]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: checkboxes
    id: contribute
    attributes:
      label: Will you be willing to contribute this feature?
      description: The feature has a much higher chance of completion if you are willing to get involved!
      options:
        - label: Yes, I will try to implement it
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
